"""
Seed script — inserts mock restaurant data + mock sources for development.
Usage: poetry run python -m app.workers.seed
"""
import asyncio
from app.core.database import AsyncSessionLocal
from app.models.place import Place, DataSource


async def clear_places(db):
    from sqlalchemy import text
    await db.execute(text("DELETE FROM data_sources"))
    await db.execute(text("DELETE FROM places"))
    await db.flush()


MOCK_PLACES = [
    {
        "name": "אבו חסן",
        "slug": "abu-hassan",
        "address": "רחוב הדולפין 1, יפו",
        "city": "תל אביב",
        "lat": 32.0520, "lng": 34.7510,
        "cuisine": ["מזרח תיכוני", "חומוס"],
        "price_range": 1,
        "phone": "03-682-0387",
        "aggregated_score": 4.9,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=אבו+חסן+יפו",
                "excerpt": "המקום הכי טוב לחומוס בישראל. תור ארוך אבל שווה כל דקה.",
                "review_count": 4821,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "rest.co.il",
                "url": "https://rest.co.il/abu-hassan",
                "excerpt": "אבו חסן הוא מוסד קולינרי. החומוס שלו נחשב לטוב ביותר בארץ כבר עשרות שנים.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "טאיזו",
        "slug": "taizu",
        "address": "רחוב מנחם בגין 23, תל אביב",
        "city": "תל אביב",
        "lat": 32.0694, "lng": 34.7925,
        "cuisine": ["פיוז׳ן אסייתי"],
        "price_range": 4,
        "phone": "03-522-5005",
        "aggregated_score": 4.8,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=טאיזו+תל+אביב",
                "excerpt": "חוויה קולינרית יוצאת דופן. האווירה, האוכל והשירות — הכל ברמה הגבוהה ביותר.",
                "review_count": 2134,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "מוסף הארץ",
                "url": "https://www.haaretz.co.il/food/taizu",
                "excerpt": "אחד מעשרת המסעדות הטובות בישראל. השף משלב טעמים אסייתיים בצורה מרהיבה.",
                "review_count": None,
                "confidence": 0.7,
            },
            {
                "source_type": "menu",
                "source_name": "Ontopo",
                "url": "https://ontopo.com/il/taizu",
                "excerpt": "תפריט: דים סאם, פאד תאי טרופי, סלמון לאוס, בקר ווגיו. ₪₪₪₪",
                "review_count": None,
                "confidence": 0.75,
            },
        ],
    },
    {
        "name": "בר החומוס",
        "slug": "the-hummus-bar",
        "address": "רחוב דיזנגוף 12, תל אביב",
        "city": "תל אביב",
        "lat": 32.0769, "lng": 34.7739,
        "cuisine": ["מזרח תיכוני", "ישראלי"],
        "price_range": 1,
        "phone": "03-123-4567",
        "aggregated_score": 4.7,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=בר+החומוס+דיזנגוף",
                "excerpt": "חומוס טרי, פלאפל פריך ומחיר מעולה. מקום חובה לכל מי שגר בסביבה.",
                "review_count": 1893,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "TimeOut ישראל",
                "url": "https://www.timeout.co.il/hummusbar",
                "excerpt": "בין עשרת מסעדות החומוס הטובות בתל אביב. המנות הצמחוניות מצוינות.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "מזנון",
        "slug": "miznon",
        "address": "רחוב המלך ג׳ורג׳ 30, תל אביב",
        "city": "תל אביב",
        "lat": 32.0706, "lng": 34.7738,
        "cuisine": ["ישראלי", "אוכל רחוב"],
        "price_range": 2,
        "phone": "03-588-0966",
        "aggregated_score": 4.6,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=מזנון+תל+אביב",
                "excerpt": "כיף ענק, אוכל טעים ומחיר סביר. הפיתות הן יצירות אמנות.",
                "review_count": 3240,
                "confidence": 0.9,
            },
            {
                "source_type": "menu",
                "source_name": "Wolt",
                "url": "https://wolt.com/he/isr/tel-aviv/restaurant/miznon",
                "excerpt": "תפריט: כרובית שלמה, גולאש פיתה, פטריות, שניצל פיתה. משלוחים זמינים.",
                "review_count": None,
                "confidence": 0.7,
            },
        ],
    },
    {
        "name": "סושי סמבה",
        "slug": "sushi-samba",
        "address": "רחוב אבן גבירול 8, תל אביב",
        "city": "תל אביב",
        "lat": 32.0853, "lng": 34.7818,
        "cuisine": ["יפני", "ברזילאי"],
        "price_range": 4,
        "phone": "03-345-6789",
        "aggregated_score": 4.5,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=סושי+סמבה+תל+אביב",
                "excerpt": "פיוז׳ן יפני-ברזילאי מרתק. הסשימי טרי להפליא וקוקטיילים מעולים.",
                "review_count": 1567,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "Xnet אוכל",
                "url": "https://xnet.ynet.co.il/food/sushi-samba",
                "excerpt": "יצירתיות יפנית עם נשמה ברזילאית. מנות הניגירי עם הטוויסט הסמבה הן חובה.",
                "review_count": None,
                "confidence": 0.6,
            },
            {
                "source_type": "menu",
                "source_name": "Tabit",
                "url": "https://tabit.cloud/sushi-samba",
                "excerpt": "תפריט: ניגירי, מאקי, סשימי, צ׳ילי קראנצ׳י, טמאקי טרופי. הזמנות שולחנות אונליין.",
                "review_count": None,
                "confidence": 0.75,
            },
        ],
    },
    {
        "name": "שילה",
        "slug": "shila",
        "address": "רחוב בן יהודה 182, תל אביב",
        "city": "תל אביב",
        "lat": 32.0877, "lng": 34.7726,
        "cuisine": ["ים תיכוני", "פירות ים"],
        "price_range": 3,
        "phone": "03-522-1224",
        "aggregated_score": 4.4,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=שילה+בן+יהודה",
                "excerpt": "מסעדת ים תיכונית מצוינת עם נוף לים. הדג הטרי מגיע ישירות מהנמל.",
                "review_count": 987,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "וואלה! אוכל",
                "url": "https://food.walla.co.il/shila",
                "excerpt": "שילה מציעה חוויה ים תיכונית אותנטית. מרק הדגים שלהם זכה בפרס מסעדת השנה.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "פסטה נוסטרה",
        "slug": "pasta-nostra",
        "address": "שדרות רוטשילד 34, תל אביב",
        "city": "תל אביב",
        "lat": 32.0624, "lng": 34.7737,
        "cuisine": ["איטלקי"],
        "price_range": 3,
        "phone": "03-234-5678",
        "aggregated_score": 4.3,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=פסטה+נוסטרה+רוטשילד",
                "excerpt": "פסטה טרייה עשויה במקום. הטרטופו בחמאה הוא פשוט בלתי נשכח.",
                "review_count": 1102,
                "confidence": 0.9,
            },
            {
                "source_type": "menu",
                "source_name": "Ontopo",
                "url": "https://ontopo.com/il/pasta-nostra",
                "excerpt": "תפריט: ספגטי קרבונרה, ריגטוני ארביאטה, ניוקי טרפל, לזניה קלאסית. הזמנות שולחנות.",
                "review_count": None,
                "confidence": 0.7,
            },
        ],
    },
    {
        "name": "פרונטו",
        "slug": "pronto",
        "address": "רחוב הרצל 4, תל אביב",
        "city": "תל אביב",
        "lat": 32.0664, "lng": 34.7697,
        "cuisine": ["איטלקי", "פיצה"],
        "price_range": 2,
        "phone": "03-566-0915",
        "aggregated_score": 4.2,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=פרונטו+הרצל",
                "excerpt": "פיצה דקה ופריכה בסגנון נאפוליטני. האווירה ססגונית ומזמינה.",
                "review_count": 876,
                "confidence": 0.9,
            },
            {
                "source_type": "menu",
                "source_name": "Wolt",
                "url": "https://wolt.com/he/isr/tel-aviv/restaurant/pronto",
                "excerpt": "תפריט: מרגריטה, פנגי, קוואטרו פורמאג׳י, ברוסקטה. משלוחים עד 23:00.",
                "review_count": None,
                "confidence": 0.7,
            },
        ],
    },
    # ── additional restaurants ────────────────────────────────────────────
    {
        "name": "פורט סעיד",
        "slug": "port-said",
        "address": "רחוב ביאליק 5, תל אביב",
        "city": "תל אביב",
        "lat": 32.0671, "lng": 34.7736,
        "cuisine": ["ישראלי", "אוכל רחוב"],
        "price_range": 2,
        "phone": "03-560-0992",
        "aggregated_score": 4.7,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=פורט+סעיד+תל+אביב",
                "excerpt": "ממסעדות הדגל של תל אביב. אווירה תוססת, תפריט ישראלי יצירתי ושירות ברמה גבוהה.",
                "review_count": 3876,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "TimeOut ישראל",
                "url": "https://www.timeout.co.il/port-said",
                "excerpt": "פורט סעיד הוא הגדרה מחדש של האוכל הישראלי. הכריך הדגים של אייל שני הוא אייקון קולינרי.",
                "review_count": None,
                "confidence": 0.7,
            },
            {
                "source_type": "menu",
                "source_name": "Wolt",
                "url": "https://wolt.com/he/isr/tel-aviv/restaurant/port-said",
                "excerpt": "תפריט: כריך דג, חצילים, ביצת עין, לחם טוסט. משלוחים עד חצות.",
                "review_count": None,
                "confidence": 0.7,
            },
        ],
    },
    {
        "name": "ננוצ'קה",
        "slug": "nanuchka",
        "address": "רחוב ליליינבלום 28, תל אביב",
        "city": "תל אביב",
        "lat": 32.0641, "lng": 34.7718,
        "cuisine": ["גיאורגי", "טבעוני"],
        "price_range": 2,
        "phone": "03-516-2254",
        "aggregated_score": 4.5,
        "photos": [
            "https://nanuchka.co.il/wp-content/uploads/2026/09/unnamed-file-6-300x200.jpg",
            "https://nanuchka.co.il/wp-content/uploads/2026/09/unnamed-file-5-300x200.jpg",
            "https://nanuchka.co.il/wp-content/uploads/2026/09/unnamed-file-4-300x200.jpg",
            "https://nanuchka.co.il/wp-content/uploads/2026/09/unnamed-file-32-300x200.jpg",
        ],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=ננוצ'קה+תל+אביב",
                "excerpt": "מסעדה גיאורגית ייחודית עם אווירה חמה ומוזיקה חיה. הכנה חלאצ'פורי הוא חובה.",
                "review_count": 2341,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "הארץ",
                "url": "https://www.haaretz.co.il/food/nanuchka",
                "excerpt": "ננוצ'קה היא אחת המסעדות הוותיקות והאהובות של תל אביב. הפכה לטבעונית לחלוטין ב-2014.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "קיצ'ן מרקט",
        "slug": "kitchen-market",
        "address": "שוק הכרמל, רחוב הכרמל 10, תל אביב",
        "city": "תל אביב",
        "lat": 32.0650, "lng": 34.7695,
        "cuisine": ["ישראלי", "ים תיכוני"],
        "price_range": 3,
        "phone": "03-752-6767",
        "aggregated_score": 4.6,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=קיצ'ן+מרקט+כרמל",
                "excerpt": "גן עדן לאוהבי אוכל. מיקום מושלם בתוך שוק הכרמל, חומרי גלם טריים ומנות יצירתיות.",
                "review_count": 1654,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "וואלה! אוכל",
                "url": "https://food.walla.co.il/kitchen-market",
                "excerpt": "קיצ'ן מרקט מציע חוויית אוכל ישראלית אותנטית. הממוקם בלב שוק הכרמל.",
                "review_count": None,
                "confidence": 0.65,
            },
            {
                "source_type": "menu",
                "source_name": "Ontopo",
                "url": "https://ontopo.com/il/kitchen-market",
                "excerpt": "תפריט: סביצ'ה, טרטר, פסטה טרייה, קינוחים מהשוק. תפריט משתנה יומית.",
                "review_count": None,
                "confidence": 0.7,
            },
        ],
    },
    {
        "name": "הבסטה",
        "slug": "habasta",
        "address": "רחוב שלמה המלך 4, תל אביב",
        "city": "תל אביב",
        "lat": 32.0658, "lng": 34.7700,
        "cuisine": ["ים תיכוני", "ישראלי"],
        "price_range": 3,
        "phone": "03-516-6966",
        "aggregated_score": 4.8,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=הבסטה+תל+אביב",
                "excerpt": "מסעדה מדהימה ליד שוק הכרמל. תפריט עונתי מרשים, יין מעולה ואווירה אינטימית.",
                "review_count": 1987,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "מוסף הארץ",
                "url": "https://www.haaretz.co.il/food/habasta",
                "excerpt": "הבסטה נחשבת לאחת ממסעדות הביסטרו הטובות בתל אביב. השף מכין הכל על הרגע.",
                "review_count": None,
                "confidence": 0.7,
            },
        ],
    },
    {
        "name": "קלארו",
        "slug": "claro",
        "address": "רחוב ההשכלה 23, תל אביב",
        "city": "תל אביב",
        "lat": 32.0720, "lng": 34.7892,
        "cuisine": ["לטיני", "בשרי"],
        "price_range": 4,
        "phone": "03-360-0777",
        "aggregated_score": 4.6,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=קלארו+תל+אביב",
                "excerpt": "מסעדת בשרים לטינית יוקרתית. הבשר מגיע ישירות מדרום אמריקה, צליה מושלמת.",
                "review_count": 1432,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "Xnet אוכל",
                "url": "https://xnet.ynet.co.il/food/claro",
                "excerpt": "קלארו הוא יעד חובה לאוהבי בשר. הפיצה ארגנטינאית והמדיום-רייר שלהם הם פשוט בלתי נשכחים.",
                "review_count": None,
                "confidence": 0.6,
            },
            {
                "source_type": "menu",
                "source_name": "Tabit",
                "url": "https://tabit.cloud/claro",
                "excerpt": "תפריט: אסאדו, פיצה ארגנטינאית, אמפנדס, צ'ורסו. הזמנות שולחנות אונליין.",
                "review_count": None,
                "confidence": 0.75,
            },
        ],
    },
    {
        "name": "רומנו",
        "slug": "romano",
        "address": "שדרות רוטשילד 6, תל אביב",
        "city": "תל אביב",
        "lat": 32.0624, "lng": 34.7737,
        "cuisine": ["איטלקי", "ישראלי"],
        "price_range": 3,
        "phone": "03-525-3535",
        "aggregated_score": 4.7,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=רומנו+רוטשילד+תל+אביב",
                "excerpt": "אייל שני מפגיש בין האיטלקי לישראלי. הפסטה טרייה, הבצק מושלם והאווירה תוססת.",
                "review_count": 2876,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "TimeOut ישראל",
                "url": "https://www.timeout.co.il/romano",
                "excerpt": "רומנו של אייל שני ברוטשילד — ניסוי מוצלח בפיוז׳ן ישראלי-איטלקי. לא מחמיצים.",
                "review_count": None,
                "confidence": 0.7,
            },
            {
                "source_type": "menu",
                "source_name": "Ontopo",
                "url": "https://ontopo.com/il/romano",
                "excerpt": "תפריט: פסטה טרייה, פיצה ישראלית, אנטיפסטי, קינוחים. הזמנות מקוונות.",
                "review_count": None,
                "confidence": 0.75,
            },
        ],
    },
    {
        "name": "ד\"ר שקשוקה",
        "slug": "dr-shakshuka",
        "address": "רחוב בית לחם 3, יפו",
        "city": "תל אביב",
        "lat": 32.0498, "lng": 34.7514,
        "cuisine": ["ישראלי", "ארוחת בוקר"],
        "price_range": 1,
        "phone": "03-682-2842",
        "aggregated_score": 4.6,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=דר+שקשוקה+יפו",
                "excerpt": "מסעדה ליבית אגדית ביפו. שקשוקה בסגנון לובי, כוסכוס ביתי ואווירה של פעם.",
                "review_count": 3421,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "הארץ",
                "url": "https://www.haaretz.co.il/food/dr-shakshuka",
                "excerpt": "מוסד תרבותי ביפו. ד\"ר שקשוקה פועל כבר עשרות שנים ומציע מטבח לובי-ישראלי אמיתי.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "דלאל",
        "slug": "dallal",
        "address": "רחוב שמעון 10, יפו",
        "city": "תל אביב",
        "lat": 32.0512, "lng": 34.7520,
        "cuisine": ["צרפתי", "ים תיכוני"],
        "price_range": 3,
        "phone": "03-682-1545",
        "aggregated_score": 4.5,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=דלאל+יפו+תל+אביב",
                "excerpt": "ביסטרו צרפתי בלב יפו העתיקה. בניין בוטיק שמור, אוכל עם השפעות ים-תיכוניות.",
                "review_count": 1654,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "וואלה! אוכל",
                "url": "https://food.walla.co.il/dallal",
                "excerpt": "דלאל מציע חוויה צרפתית אותנטית בסביבה יפואית. קינוחי הפטיסרי שלהם מדהימים.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "בנדיקט",
        "slug": "benedict",
        "address": "רחוב ביאליק 29, תל אביב",
        "city": "תל אביב",
        "lat": 32.0667, "lng": 34.7730,
        "cuisine": ["ארוחת בוקר", "ישראלי"],
        "price_range": 2,
        "phone": "03-686-8657",
        "aggregated_score": 4.4,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=בנדיקט+תל+אביב",
                "excerpt": "ארוחת בוקר כל היום, כל הלילה. ביצים בנדיקט, פנקייקים ואומלטים בסגנון ביתי.",
                "review_count": 4102,
                "confidence": 0.9,
            },
            {
                "source_type": "menu",
                "source_name": "Wolt",
                "url": "https://wolt.com/he/isr/tel-aviv/restaurant/benedict",
                "excerpt": "תפריט: ביצים בנדיקט, שאקשוקה, פנקייקים, צרפתי, ביצה עצבנית. 24/7.",
                "review_count": None,
                "confidence": 0.7,
            },
        ],
    },
    {
        "name": "הקוסם",
        "slug": "ha-kosem",
        "address": "שדרות רוטשילד 21, תל אביב",
        "city": "תל אביב",
        "lat": 32.0638, "lng": 34.7734,
        "cuisine": ["פלאפל", "ישראלי"],
        "price_range": 1,
        "phone": "03-525-1234",
        "aggregated_score": 4.7,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=הקוסם+פלאפל+תל+אביב",
                "excerpt": "הפלאפל הכי טרי בתל אביב. כדורים פריכים, חומוס עשיר ושתייה קרה בצד.",
                "review_count": 2198,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "TimeOut ישראל",
                "url": "https://www.timeout.co.il/ha-kosem",
                "excerpt": "הקוסם נחשב לפלאפל הכי טוב בתל אביב. התור בצהריים ארוך אבל שווה.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "ברוטו",
        "slug": "bruto",
        "address": "רחוב טשרניחובסקי 36, תל אביב",
        "city": "תל אביב",
        "lat": 32.0762, "lng": 34.7786,
        "cuisine": ["איטלקי", "פסטה"],
        "price_range": 3,
        "phone": "03-544-4141",
        "aggregated_score": 4.6,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=ברוטו+תל+אביב",
                "excerpt": "בר פסטה איטלקי ים-תיכוני. מקרוני בחמאה שחורה, קרבונרה אמיתית, רביולי של השף.",
                "review_count": 1843,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "מוסף הארץ",
                "url": "https://www.haaretz.co.il/food/bruto",
                "excerpt": "ברוטו הוא מסעדת הפסטה שתל אביב חיכתה לה. פשוט, ישיר, ומדהים.",
                "review_count": None,
                "confidence": 0.7,
            },
            {
                "source_type": "menu",
                "source_name": "Ontopo",
                "url": "https://ontopo.com/il/bruto",
                "excerpt": "תפריט: טונרלי, ספגטי אמטריצ'אנה, ריגטוני קרבונרה, טירמיסו. הזמנות שולחנות.",
                "review_count": None,
                "confidence": 0.75,
            },
        ],
    },
    {
        "name": "קאטית",
        "slug": "catit",
        "address": "רחוב הרב קוק 4, תל אביב",
        "city": "תל אביב",
        "lat": 32.0635, "lng": 34.7718,
        "cuisine": ["ישראלי", "שף"],
        "price_range": 4,
        "phone": "03-510-7001",
        "aggregated_score": 4.8,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=קאטית+תל+אביב",
                "excerpt": "מסעדת שף פרימיום של מאיר עדוני. יצירתיות, דיוק ושימוש בחומרי הגלם הטובים ביותר.",
                "review_count": 987,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "מוסף הארץ",
                "url": "https://www.haaretz.co.il/food/catit",
                "excerpt": "קאטית של מאיר עדוני היא מסעדת שף ישראלית ברמה בינלאומית. כל ביקור הוא חוויה.",
                "review_count": None,
                "confidence": 0.75,
            },
            {
                "source_type": "menu",
                "source_name": "Tabit",
                "url": "https://tabit.cloud/catit",
                "excerpt": "תפריט דגשים: תפריט טעימות 7 מנות, תפריט צמחוני, יין ישראלי נבחר. הזמנה מראש חובה.",
                "review_count": None,
                "confidence": 0.8,
            },
        ],
    },
    {
        "name": "אגדיר",
        "slug": "agadir",
        "address": "שדרות בן גוריון 23, תל אביב",
        "city": "תל אביב",
        "lat": 32.0897, "lng": 34.7743,
        "cuisine": ["המבורגר", "בשרי"],
        "price_range": 2,
        "phone": "03-544-9292",
        "aggregated_score": 4.3,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=אגדיר+בן+גוריון+תל+אביב",
                "excerpt": "המבורגר גורמה בסגנון אמריקאי. הבשר טרי, הלחמנייה פריכה ורטבי הבית מיוחדים.",
                "review_count": 3102,
                "confidence": 0.9,
            },
            {
                "source_type": "menu",
                "source_name": "Wolt",
                "url": "https://wolt.com/he/isr/tel-aviv/restaurant/agadir",
                "excerpt": "תפריט: קלאסיק, ביקון צ'יז, פטריות שוויצרי, טבעוני. משלוחים עד 23:30.",
                "review_count": None,
                "confidence": 0.7,
            },
        ],
    },
    {
        "name": "שקשוקיה",
        "slug": "shakshukiya",
        "address": "רחוב הכרמל 12, תל אביב",
        "city": "תל אביב",
        "lat": 32.0647, "lng": 34.7692,
        "cuisine": ["ארוחת בוקר", "ישראלי"],
        "price_range": 2,
        "phone": "03-525-6660",
        "aggregated_score": 4.5,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=שקשוקיה+כרמל+תל+אביב",
                "excerpt": "שקשוקה בגרסאות אין-סוף: אדומה, ירוקה, שחורה, גבינות. מיקום מושלם ליד שוק הכרמל.",
                "review_count": 1876,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "TimeOut ישראל",
                "url": "https://www.timeout.co.il/shakshukiya",
                "excerpt": "שקשוקיה היא ממסעדות הבוקר האהובות של תל אביב. בין עשרת הטובות בעיר.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "קלמטה",
        "slug": "kalamata",
        "address": "רחוב יבנה 15, תל אביב",
        "city": "תל אביב",
        "lat": 32.0672, "lng": 34.7760,
        "cuisine": ["יווני", "ים תיכוני"],
        "price_range": 3,
        "phone": "03-566-9777",
        "aggregated_score": 4.4,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=קלמטה+תל+אביב",
                "excerpt": "מסעדה יוונית אותנטית עם מזה, דגים טריים וצוצוקי נהדר. חוויה ים-תיכונית מלאה.",
                "review_count": 1234,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "וואלה! אוכל",
                "url": "https://food.walla.co.il/kalamata",
                "excerpt": "קלמטה מביאה את יוון לתל אביב. הטאפנד, הפיטה והמוסקה — הכל כמו בסנטוריני.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "אוזריה",
        "slug": "ouzeria",
        "address": "רחוב לילינבלום 35, תל אביב",
        "city": "תל אביב",
        "lat": 32.0639, "lng": 34.7715,
        "cuisine": ["יווני", "בר"],
        "price_range": 3,
        "phone": "03-516-5505",
        "aggregated_score": 4.3,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=אוזריה+לילינבלום+תל+אביב",
                "excerpt": "בר אוזו יווני עם מזה קטנות, ראקי וצ'ופיטו. אווירה חגיגית ורעשנית עד שעות הקטנות.",
                "review_count": 1102,
                "confidence": 0.9,
            },
        ],
    },
    {
        "name": "ביציקלטה",
        "slug": "bicicletta",
        "address": "רחוב ביאליק 2, תל אביב",
        "city": "תל אביב",
        "lat": 32.0671, "lng": 34.7737,
        "cuisine": ["איטלקי", "פיצה"],
        "price_range": 2,
        "phone": "03-522-3031",
        "aggregated_score": 4.4,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=ביציקלטה+תל+אביב",
                "excerpt": "פיצרייה איטלקית אותנטית. הבצק מחמצת, הרוטב עגבניות סן מרצאנו, מוצרלה פרסקה.",
                "review_count": 1543,
                "confidence": 0.9,
            },
            {
                "source_type": "menu",
                "source_name": "Wolt",
                "url": "https://wolt.com/he/isr/tel-aviv/restaurant/bicicletta",
                "excerpt": "תפריט: מרגריטה DOC, נאפוליטנה, קלצוני, ארנצ'יני. משלוחים עד 23:00.",
                "review_count": None,
                "confidence": 0.7,
            },
        ],
    },
    {
        "name": "סאלה תאי",
        "slug": "sala-thai",
        "address": "רחוב בוגרשוב 12, תל אביב",
        "city": "תל אביב",
        "lat": 32.0770, "lng": 34.7741,
        "cuisine": ["תאילנדי", "אסייתי"],
        "price_range": 2,
        "phone": "03-620-4455",
        "aggregated_score": 4.5,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=סאלה+תאי+תל+אביב",
                "excerpt": "מסעדה תאילנדית בעלת שם. קארי ירוק עשיר, טום קא נהדר ופאד תאי של ספרי לימוד.",
                "review_count": 1876,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "TimeOut ישראל",
                "url": "https://www.timeout.co.il/sala-thai",
                "excerpt": "סאלה תאי היא הכתובת לאוכל תאילנדי אמיתי בתל אביב. ותיקה ואהובה.",
                "review_count": None,
                "confidence": 0.65,
            },
        ],
    },
    {
        "name": "קפה נואר",
        "slug": "cafe-noir",
        "address": "רחוב ארלוזורוב 43, תל אביב",
        "city": "תל אביב",
        "lat": 32.0834, "lng": 34.7812,
        "cuisine": ["צרפתי", "ביסטרו"],
        "price_range": 2,
        "phone": "03-696-6018",
        "aggregated_score": 4.3,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=קפה+נואר+תל+אביב",
                "excerpt": "ביסטרו צרפתי קלאסי. קרואסון חמאה, אוף-א-פו ואווירה של פריז בבוקר תל-אביבי.",
                "review_count": 2341,
                "confidence": 0.9,
            },
        ],
    },
    {
        "name": "מסה",
        "slug": "messa",
        "address": "שדרות הנשיא 8, תל אביב",
        "city": "תל אביב",
        "lat": 32.0785, "lng": 34.7901,
        "cuisine": ["ישראלי", "שף"],
        "price_range": 4,
        "phone": "03-685-6859",
        "aggregated_score": 4.7,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=מסה+תל+אביב",
                "excerpt": "מסעדת שף יוקרתית עם תפריט ישראלי קונטמפוררי. כל מנה היא יצירת אמנות.",
                "review_count": 1102,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "מוסף הארץ",
                "url": "https://www.haaretz.co.il/food/messa",
                "excerpt": "מסה היא אחת ממסעדות השף הנחשבות בישראל. החוויה הגסטרונומית כאן חסרת פשרות.",
                "review_count": None,
                "confidence": 0.75,
            },
            {
                "source_type": "menu",
                "source_name": "Tabit",
                "url": "https://tabit.cloud/messa",
                "excerpt": "תפריט עונתי משתנה. הזמנה מראש מומלצת מאוד. תפריט טעימות 5 מנות זמין.",
                "review_count": None,
                "confidence": 0.8,
            },
        ],
    },
    {
        "name": "האוז'ריה",
        "slug": "the-fish-restaurant",
        "address": "נמל יפו, תל אביב",
        "city": "תל אביב",
        "lat": 32.0480, "lng": 34.7520,
        "cuisine": ["פירות ים", "ים תיכוני"],
        "price_range": 3,
        "phone": "03-681-6666",
        "aggregated_score": 4.4,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=מסעדת+דגים+נמל+יפו",
                "excerpt": "דגים טריים ישירות מהנמל. דניס, לברק, שרימפס בגריל — הכל טרי של הבוקר.",
                "review_count": 987,
                "confidence": 0.9,
            },
        ],
    },
    {
        "name": "השולחן",
        "slug": "ha-shulchan",
        "address": "רחוב שלמה המלך 7, תל אביב",
        "city": "תל אביב",
        "lat": 32.0660, "lng": 34.7705,
        "cuisine": ["ישראלי", "ים תיכוני"],
        "price_range": 3,
        "phone": "03-516-3636",
        "aggregated_score": 4.5,
        "photos": [],
        "sources": [
            {
                "source_type": "google_places",
                "source_name": "Google",
                "url": "https://maps.google.com/?q=השולחן+תל+אביב",
                "excerpt": "מסעדה ישראלית קונטמפוררית עם חומרי גלם מהשוק. תפריט עונתי, יין טוב ואווירה חמה.",
                "review_count": 1432,
                "confidence": 0.9,
            },
            {
                "source_type": "article",
                "source_name": "Xnet אוכל",
                "url": "https://xnet.ynet.co.il/food/ha-shulchan",
                "excerpt": "השולחן מוכיח שאפשר לאכול ישראלי ברמה גבוהה בלי לשלם מחיר שף. יחס מצוין.",
                "review_count": None,
                "confidence": 0.6,
            },
        ],
    },
]


async def seed():
    async with AsyncSessionLocal() as db:
        await clear_places(db)
        for data in MOCK_PLACES:
            sources_data = data.pop("sources", [])
            place = Place(**data)
            db.add(place)
            await db.flush()
            for s in sources_data:
                db.add(DataSource(place_id=place.id, **s))
        await db.commit()
        print(f"נזרעו {len(MOCK_PLACES)} מסעדות עם מקורות.")


if __name__ == "__main__":
    asyncio.run(seed())
