"""add_saved_places_and_user_preferences

Revision ID: 633eeee5fd59
Revises: 49b41530ad79
Create Date: 2026-10-07 12:52:23.994566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '633eeee5fd59'
down_revision: Union[str, None] = '49b41530ad79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('list_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'place_id', 'list_type', name='uq_user_place_list')
    )
    op.create_index(op.f('ix_saved_places_place_id'), 'saved_places', ['place_id'], unique=False)
    op.create_index(op.f('ix_saved_places_user_id'), 'saved_places', ['user_id'], unique=False)
    op.add_column('users', sa.Column('cuisine_preferences', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('dietary_restrictions', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('price_preference', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'price_preference')
    op.drop_column('users', 'dietary_restrictions')
    op.drop_column('users', 'cuisine_preferences')
    op.drop_index(op.f('ix_saved_places_user_id'), table_name='saved_places')
    op.drop_index(op.f('ix_saved_places_place_id'), table_name='saved_places')
    op.drop_table('saved_places')
    # ### end Alembic commands ###
