"""datasource_enrich

Revision ID: b78cbd34a329
Revises: d0d233f1a28a
Create Date: 2026-10-05 16:52:31.493309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b78cbd34a329'
down_revision: Union[str, None] = 'd0d233f1a28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('source_name', sa.String(length=100), nullable=True))
    op.add_column('data_sources', sa.Column('excerpt', sa.Text(), nullable=True))
    op.add_column('data_sources', sa.Column('review_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'review_count')
    op.drop_column('data_sources', 'excerpt')
    op.drop_column('data_sources', 'source_name')
    # ### end Alembic commands ###
