"""add user_visits

Revision ID: bfbb7241997b
Revises: ebc1f018ed46
Create Date: 2026-10-06 22:26:53.237845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bfbb7241997b'
down_revision: Union[str, None] = 'ebc1f018ed46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_visits_place_id'), 'user_visits', ['place_id'], unique=False)
    op.create_index(op.f('ix_user_visits_user_id'), 'user_visits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_visits_user_id'), table_name='user_visits')
    op.drop_index(op.f('ix_user_visits_place_id'), table_name='user_visits')
    op.drop_table('user_visits')
    # ### end Alembic commands ###
