"""add place_ratings

Revision ID: ebc1f018ed46
Revises: b78cbd34a329
Create Date: 2026-10-06 16:45:19.900710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ebc1f018ed46'
down_revision: Union[str, None] = 'b78cbd34a329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_ratings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'place_id', name='uq_user_place_rating')
    )
    op.create_index(op.f('ix_place_ratings_place_id'), 'place_ratings', ['place_id'], unique=False)
    op.create_index(op.f('ix_place_ratings_user_id'), 'place_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_ratings_user_id'), table_name='place_ratings')
    op.drop_index(op.f('ix_place_ratings_place_id'), table_name='place_ratings')
    op.drop_table('place_ratings')
    # ### end Alembic commands ###
